/**
 * Solid fallback / "uncovered top" fill per {@link com.game.model.map.TerrainType#fallbackMapColor()}
 * (via each tile's {@code Mobility#fallbackColor} in Java).
 */
const OPEN = 0x74b058;
const FOREST_HILLS = 0x397a37;
const CANYON = 0x828282;
const BRIDGE = 0x4186c9;
const HIGH_BRIDGE = 0x58a8c6;
const MOUNTAIN = 0x6e6e78;
const SEA = 0x4186c9;
const REEF = 0x58a8c6;
const SHORE = 0x828282;
const ARCHIPELAGO = 0x58a8c6;

const BY_TERRAIN_NAME: Record<string, number> = {
  ARCHIPELAGO_2: ARCHIPELAGO,
  BRIDGE_DOWN: BRIDGE,
  BRIDGE_HORIZONTAL: BRIDGE,
  BRIDGE_LEFT: BRIDGE,
  BRIDGE_LEFTRIGHT: BRIDGE,
  BRIDGE_RIGHT: BRIDGE,
  BRIDGE_UP: BRIDGE,
  BRIDGE_UPDOWN: BRIDGE,
  BRIDGE_VERTICAL: BRIDGE,
  CANYON_DOUBLE_LEFTDOWN: CANYON,
  CANYON_DOUBLE_LEFTDOWN_ONE_RIGHTUP: CANYON,
  CANYON_DOUBLE_LEFTRIGHT: CANYON,
  CANYON_DOUBLE_LEFTUP: CANYON,
  CANYON_DOUBLE_LEFTUP_ONE_RIGHTDOWN: CANYON,
  CANYON_DOUBLE_RIGHTDOWN: CANYON,
  CANYON_DOUBLE_RIGHTDOWN_ONE_LEFTUP: CANYON,
  CANYON_DOUBLE_RIGHTUP: CANYON,
  CANYON_DOUBLE_RIGHTUP_ONE_LEFTDOWN: CANYON,
  CANYON_DOUBLE_UPDOWN: CANYON,
  CANYON_MAIN: CANYON,
  CANYON_ONE_LEFTDOWN: CANYON,
  CANYON_ONE_LEFTDOWN_ONE_RIGHTDOWN: CANYON,
  CANYON_ONE_LEFTDOWN_ONE_RIGHTUP: CANYON,
  CANYON_ONE_LEFTDOWN_ONE_RIGHTUP_ONE_RIGHTDOWN: CANYON,
  CANYON_ONE_LEFTUP: CANYON,
  CANYON_ONE_LEFTUP_ONE_LEFTDOWN: CANYON,
  CANYON_ONE_LEFTUP_ONE_LEFTDOWN_ONE_RIGHTDOWN: CANYON,
  CANYON_ONE_LEFTUP_ONE_LEFTDOWN_ONE_RIGHTUP: CANYON,
  FOREST_1: FOREST_HILLS,
  FOREST_2: FOREST_HILLS,
  HIGH_BRIDGE_DOWN: HIGH_BRIDGE,
  HIGH_BRIDGE_HORIZONTAL: HIGH_BRIDGE,
  HILLS_1: FOREST_HILLS,
  HILLS_2: FOREST_HILLS,
  MOUNTAINS_1: MOUNTAIN,
  PLAINS_1: OPEN,
  REEF_1: REEF,
  ROCK_FORMATION_1: MOUNTAIN,
  SEA_MAIN: SEA,
  SHORE_DOUBLE_LEFTDOWN: SHORE,
  SHORE_DOUBLE_LEFTUP: SHORE,
  SHORE_DOUBLE_RIGHTDOWN: SHORE,
  SHORE_DOUBLE_RIGHTUP: SHORE,
  SHORE_SINGLE_DOWN: SHORE,
  SHORE_SINGLE_LEFT: SHORE,
  SHORE_TRIPLE_DOWN: SHORE,
  SHORE_TRIPLE_LEFT: SHORE,
  SHORE_TRIPLE_RIGHT: SHORE,
  SHORE_TRIPLE_UP: SHORE,
};

const DEFAULT = OPEN;

function terrainFallbackRgbFromPrefixes(terrainEnumName: string): number | undefined {
  if (terrainEnumName.startsWith("SEA_")) {
    return SEA;
  }
  if (terrainEnumName.startsWith("REEF_")) {
    return REEF;
  }
  if (terrainEnumName.startsWith("ARCHIPELAGO_")) {
    return ARCHIPELAGO;
  }
  if (terrainEnumName.startsWith("SHORE_")) {
    return SHORE;
  }
  if (terrainEnumName.startsWith("DEPLETED_ORE_DEPOSIT")) {
    return 0x8b7d6b;
  }
  if (terrainEnumName.startsWith("ORE_DEPOSIT") || terrainEnumName.startsWith("ENRICHED_ORE_DEPOSIT")) {
    return OPEN;
  }
  if (terrainEnumName === "VOLCANO" || terrainEnumName.startsWith("ROCK_FORMATION_")) {
    return MOUNTAIN;
  }
  if (terrainEnumName === "WASTELAND") {
    return OPEN;
  }
  return undefined;
}

export function terrainFallbackRgb(terrainEnumName: string): number {
  return (
    BY_TERRAIN_NAME[terrainEnumName] ?? terrainFallbackRgbFromPrefixes(terrainEnumName) ?? DEFAULT
  );
}
